name: Test reset Neon branch

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reset-test-branch:
    runs-on: ubuntu-24.04

    steps:
      - name: Reset Neon test branch
        uses: neondatabase/reset-branch-action@v1
        id: reset-branch
        with:
          project_id: still-tooth-45133513
          branch: br-orange-night-adc3ve89
          parent: true
          api_key: ${{ secrets.NEON_API_KEY }}
          cs_role_name: admin_api_user
          
      - name: Show connection string
        run: |
          echo "Branch ID:             ${{ steps.reset-branch.outputs.branch_id }}"
          echo "DB URL:                ${{ steps.reset-branch.outputs.db_url }}"
          echo "DB URL with pooler:    ${{ steps.reset-branch.outputs.db_url_with_pooler }}"
          echo "Host:                  ${{ steps.reset-branch.outputs.host }}"
          echo "Host with pooler:      ${{ steps.reset-branch.outputs.host_with_pooler }}"
          echo "Password:              ${{ steps.reset-branch.outputs.password }}"
